module.exports = {
	purge: {
		content: ["./src/assets/**/*.js", "./src/assets/**/*.css"],
		options: {
			whitelist: ["bg-red-500", "px-4"],
		},
	},
	theme: {
		screens: {
			sm: "640px",
			md: "768px",
			lg: "1024px",
			xl: "1280px",
			xxl: "1440px",
		},
		colors: {
			transparent: "var(--color-transparent)",
			current: "currentColor",

			black: "var(--color-black)",
			white: "var(--color-white)",

			neutral: {
				"000": "var(--color-neutral-000)",
				"100": "var(--color-neutral-100)",
				"200": "var(--color-neutral-200)",
				"300": "var(--color-neutral-300)",
				"400": "var(--color-neutral-400)",
				"500": "var(--color-neutral-500)",
				"600": "var(--color-neutral-600)",
				"700": "var(--color-neutral-700)",
				"800": "var(--color-neutral-800)",
				"900": "var(--color-neutral-900)",
			},
			primary: {
				"000": "var(--color-primary-000)",
				"100": "var(--color-primary-100)",
				"200": "var(--color-primary-200)",
				"300": "var(--color-primary-300)",
				"400": "var(--color-primary-400)",
				"500": "var(--color-primary-500)",
				"600": "var(--color-primary-600)",
				"700": "var(--color-primary-700)",
				"800": "var(--color-primary-800)",
				"900": "var(--color-primary-900)",
			},
			success: {
				"000": "var(--color-success-000)",
				"100": "var(--color-success-100)",
				"200": "var(--color-success-200)",
				"300": "var(--color-success-300)",
				"400": "var(--color-success-400)",
				"500": "var(--color-success-500)",
				"600": "var(--color-success-600)",
				"700": "var(--color-success-700)",
				"800": "var(--color-success-800)",
				"900": "var(--color-success-900)",
			},
			warning: {
				"000": "var(--color-warning-000)",
				"100": "var(--color-warning-100)",
				"200": "var(--color-warning-200)",
				"300": "var(--color-warning-300)",
				"400": "var(--color-warning-400)",
				"500": "var(--color-warning-500)",
				"600": "var(--color-warning-600)",
				"700": "var(--color-warning-700)",
				"800": "var(--color-warning-800)",
				"900": "var(--color-warning-900)",
			},
			danger: {
				"000": "var(--color-danger-000)",
				"100": "var(--color-danger-100)",
				"200": "var(--color-danger-200)",
				"300": "var(--color-danger-300)",
				"400": "var(--color-danger-400)",
				"500": "var(--color-danger-500)",
				"600": "var(--color-danger-600)",
				"700": "var(--color-danger-700)",
				"800": "var(--color-danger-800)",
				"900": "var(--color-danger-900)",
			},
			info: {
				"000": "var(--color-info-000)",
				"100": "var(--color-info-100)",
				"200": "var(--color-info-200)",
				"300": "var(--color-info-300)",
				"400": "var(--color-info-400)",
				"500": "var(--color-info-500)",
				"600": "var(--color-info-600)",
				"700": "var(--color-info-700)",
				"800": "var(--color-info-800)",
				"900": "var(--color-info-900)",
			},
			urge: {
				"000": "var(--color-urge-000)",
				"100": "var(--color-urge-100)",
				"200": "var(--color-urge-200)",
				"300": "var(--color-urge-300)",
				"400": "var(--color-urge-400)",
				"500": "var(--color-urge-500)",
				"600": "var(--color-urge-600)",
				"700": "var(--color-urge-700)",
				"800": "var(--color-urge-800)",
				"900": "var(--color-urge-900)",
			},
		},
		spacing: {
			px: "var(--spacing-px)",
			"0": "var(--spacing-0)",
			"1": "var(--spacing-1)",
			"2": "var(--spacing-2)",
			"3": "var(--spacing-3)",
			"4": "var(--spacing-4)",
			"5": "var(--spacing-5)",
			"6": "var(--spacing-6)",
			"8": "var(--spacing-8)",
			"10": "var(--spacing-10)",
			"12": "var(--spacing-12)",
			"16": "var(--spacing-16)",
			"20": "var(--spacing-20)",
			"24": "var(--spacing-24)",
			"32": "var(--spacing-32)",
			"40": "var(--spacing-40)",
			"48": "var(--spacing-48)",
			"56": "var(--spacing-56)",
			"64": "var(--spacing-64)",
			"72": "var(--spacing-72)",
			"84": "var(--spacing-84)",
			"96": "var(--spacing-96)",
		},
		borderRadius: {
			none: "var(--border-radius-none)",
			sm: "var(--border-radius-sm)",
			default: "var(--border-radius-default)",
			md: "var(--border-radius-md)",
			lg: "var(--border-radius-lg)",
			xl: "var(--border-radius-xl)",
			full: "var(--border-radius-full)",
		},
		borderWidth: {
			default: "var(--border-width-default, 1px)",
			"0": "var(--border-width-0, 0)",
			"2": "var(--border-width-2, 2px)",
			"4": "var(--border-width-4, 4px)",
			"8": "var(--border-width-8, 8px)",
		},
		boxShadow: {
			xs: "var(--box-shadow-xs)",
			sm: "var(--box-shadow-sm)",
			default: "var(--box-shadow-default)",
			md: "var(--box-shadow-md)",
			lg: "var(--box-shadow-lg)",
			xl: "var(--box-shadow-xl)",
			"2xl": "var(--box-shadow-2xl)",
			inner: "var(--box-shadow-inner)",
			outline: "var(--box-shadow-outline)",
			none: "var(--box-shadow-none)",
		},
		fontFamily: {
			primary: "var(--family-primary)",
			secondary: "var(--family-secondary)",
			sans: [
				"Inter",
				"system-ui",
				"-apple-system",
				"BlinkMacSystemFont",
				'"Segoe UI"',
				"Roboto",
				'"Helvetica Neue"',
				"Arial",
				'"Noto Sans"',
				"sans-serif",
				'"Apple Color Emoji"',
				'"Segoe UI Emoji"',
				'"Segoe UI Symbol"',
				'"Noto Color Emoji"',
			],
			serif: ["Georgia", "Cambria", '"Times New Roman"', "Times", "serif"],
			mono: ["Menlo", "Monaco", "Consolas", '"Liberation Mono"', '"Courier New"', "monospace"],
		},
		fontSize: {
			xs: "var(--font-size-xs)",
			sm: "var(--font-size-sm)",
			base: "var(--font-size-base)",
			lg: "var(--font-size-lg)",
			xl: "var(--font-size-xl)",
			"2xl": "var(--font-size-2xl)",
			"3xl": "var(--font-size-3xl)",
			"4xl": "var(--font-size-4xl)",
			"5xl": "var(--font-size-5xl)",
			"6xl": "var(--font-size-6xl)",
		},
		fontWeight: {
			hairline: "var(--font-weight-hairline)",
			thin: "var(--font-weight-thin)",
			light: "var(--font-weight-light)",
			normal: "var(--font-weight-normal)",
			medium: "var(--font-weight-medium)",
			semibold: "var(--font-weight-semibold)",
			bold: "var(--font-weight-bold)",
			extrabold: "var(--font-weight-extrabold)",
			black: "var(--font-weight-black)",
		},
		letterSpacing: {
			tighter: "var(--letter-spacing-tighter)",
			tight: "var(--letter-spacing-tight)",
			normal: "var(--letter-spacing-normal)",
			wide: "var(--letter-spacing-wide)",
			wider: "var(--letter-spacing-wider)",
			widest: "var(--letter-spacing-widest)",
		},
		lineHeight: {
			none: "var(--line-height-none)",
			tight: "var(--line-height-tight)",
			snug: "var(--line-height-snug)",
			normal: "var(--line-height-normal)",
			relaxed: "var(--line-height-relaxed)",
			loose: "var(--line-height-loose)",
			"3": "var(--line-height-3)",
			"4": "var(--line-height-4)",
			"5": "var(--line-height-5)",
			"6": "var(--line-height-6)",
			"7": "var(--line-height-7)",
			"8": "var(--line-height-8)",
			"9": "var(--line-height-9)",
			"10": "var(--line-height-10)",
		},
		maxWidth: (theme, { breakpoints }) => ({
			none: "none",
			xs: "var(--max-width-xs)",
			sm: "var(--max-width-sm)",
			md: "var(--max-width-md)",
			lg: "var(--max-width-lg)",
			xl: "var(--max-width-xl)",
			"2xl": "var(--max-width-2xl)",
			"3xl": "var(--max-width-3xl)",
			"4xl": "var(--max-width-4xl)",
			"5xl": "var(--max-width-5xl)",
			"6xl": "var(--max-width-6xl)",
			full: "100%",
			...breakpoints(theme("screens")),
		}),
		scale: {
			"0": "var(--scale-0)",
			"50": "var(--scale-50)",
			"75": "var(--scale-75)",
			"90": "var(--scale-90)",
			"95": "var(--scale-95)",
			"100": "var(--scale-100)",
			"105": "var(--scale-105)",
			"110": "var(--scale-110)",
			"125": "var(--scale-125)",
			"150": "var(--scale-150)",
		},
	},
	plugins: [],
};
